FROM python:3.9
WORKDIR /bot
RUN apt-get update -y && apt-get install -y freeglut3-dev libgtk2.0-dev nginx
RUN pip install scipy discord aiohttp aiodns opencv-python pillow requests sqlalchemy flask numpy gunicorn cchardet
RUN ln -s /bot/mosaic_bot/server/dev-server.conf /etc/nginx/sites-enabled/mosaic
RUN rm /etc/nginx/sites-enabled/default
ENV MOSAIC_USE_DEV_TOKEN=1
COPY . .
RUN pip install -e .
CMD nginx && gunicorn mosaic_bot.server.wsgi --access-logfile - --bind unix:/var/run/mosaic-server.sock
